### PR TITLE
Amend changelog for 0.2.0

### PR DESCRIPTION
**Pull request by juliusv**
To be merged after https://github.com/prometheus/promlens/pull/50

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]

**Comment by Nexucis** [comment]
Lol looks like I didn't remove enough platforms/arch

**Comment by juliusv** [comment]
Doh! Remove netbsd as well? Bit sad but...

**Comment by Nexucis** [comment]
once the changelog is updated with the last changes, we can merge this one. @juliusv let me know if you want me to tag (with the GPG key)

**Comment by juliusv** [comment]
@Nexucis Yup, I can tag + sign it now that I'm back home. Just pushed the amendment to the amendment, hopefully it looks good now :)

**Review by Nexucis — APPROVED** [review]
awesome 🥳

**Pull request merged**
